apiVersion: apps/v1
kind: Deployment
metadata:
  name: tachikoma-webserver
  labels:
    app: tachikoma-webserver
  annotations:
    buildTime: "${currentTime}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tachikoma-webserver
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: tachikoma-webserver
      annotations:
        buildTime: "${currentTime}"
    spec:
      containers:
        - name: tachikoma-webserver
          image: ${dockerRepository}/tachikoma-webserver:${version}
          imagePullPolicy: Always
          ports:
            - name: webserver-port
              protocol: TCP
              containerPort: 8070
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/ready
              httpHeaders:
                  # Make sure health checks aren't traced
                - name: traceparent
                  value: 00-11111111111111111111111111111111-1111111111111111-00
              port: 8070
              scheme: HTTP
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 10
            httpGet:
              path: /health
              port: 8070
              scheme: HTTP
              httpHeaders:
                  # Make sure health checks aren't traced
                - name: traceparent
                  value: 00-11111111111111111111111111111111-2222222222222222-00
          startupProbe:
            failureThreshold: 50
            initialDelaySeconds: 10
            httpGet:
              path: /health
              port: 8070
              scheme: HTTP
              httpHeaders:
                # Make sure health checks aren't traced
                - name: traceparent
                  value: 00-11111111111111111111111111111111-2222222222222222-00
          volumeMounts:
            - name: webserver-config
              mountPath: "/etc/tachikoma/config/"
              readOnly: true
            - name: webserver-rsyslog
              mountPath: "/etc/tachikoma/rsyslog/"
              readOnly: true
          env:
            - name: TACHIKOMA_CONFIG
              value: "/etc/tachikoma/config/tachikoma.properties"
            - name: SSL_CERT_CHAIN_FILE
              valueFrom:
                secretKeyRef:
                  key: SSL_CERT_CHAIN_FILE
                  name: tachikoma-webserver-config
                  optional: true
            - name: SSL_CERT_KEY_FILE
              valueFrom:
                secretKeyRef:
                  key: SSL_CERT_KEY_FILE
                  name: tachikoma-webserver-config
                  optional: true
      volumes:
        - name: webserver-config
          secret:
            secretName: tachikoma-webserver-config
        - name: webserver-rsyslog
          secret:
            secretName: tachikoma-webserver-rsyslog
---
apiVersion: v1
kind: Service
metadata:
  name: "tachikoma-webserver-svc"
  labels:
    app: "tachikoma"
    appName: "tachikoma"
spec:
  selector:
    # Selects all PODs that have these labels
    app: "tachikoma-webserver"
  type: NodePort
  ports:
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 8070
