apiVersion: v1
kind: Pod
metadata:
  name: tachikoma-webserver
spec:
  containers:
  - name: tachikoma-webserver
    image: sourceforgery/tachikoma-webserver:0.0.1-SNAPSHOT
    ports:
    - containerPort: 8070
    volumeMounts:
    - name: webserver-config
      mountPath: "/etc/tachikoma/config/"
      readOnly: true
    - name: webserver-certs
      mountPath: "/etc/tachikoma/cert/"
      readOnly: true
    env:
    - name: TACHIKOMA_CONFIG
      value: "/etc/tachikoma/config/tachikoma.config"
    - name: SSL_CERT_CHAIN_FILE
      value: "/etc/tachikoma/cert/server.cert"
    - name: SSL_CERT_KEY_FILE
      value: "/etc/tachikoma/cert/server.key"
  volumes:
  - name: webserver-config
    secret:
      secretName: tachikoma-webserver-config
  - name: webserver-certs
    secret:
      secretName: tachikoma-webserver-cert